# fly.toml app configuration file generated for picpop-black-fog-1159 on 2023-12-05T22:26:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "picpop-black-fog-1159"
primary_region = "arn"

[build]

[http_service]
  internal_port = 5050
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mount]
  source = "site"
  destination = "/data"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
